In [1]:
import glob
import pandas as pd

In [2]:
sort_DEGs_all_results_list = [f for f in glob.glob("DEGs/SS2/met_vs_primary/*.csv")]

In [3]:
sort_DEGs_all_results_list

['DEGs/SS2/met_vs_primary/MAST_HCI001.csv',
 'DEGs/SS2/met_vs_primary/MAST_H4272.csv',
 'DEGs/SS2/met_vs_primary/MAST_HCI009.csv',
 'DEGs/SS2/met_vs_primary/MAST_global.csv',
 'DEGs/SS2/met_vs_primary/MAST_J55454.csv',
 'DEGs/SS2/met_vs_primary/MAST_H5097.csv',
 'DEGs/SS2/met_vs_primary/MAST_HCI005.csv',
 'DEGs/SS2/met_vs_primary/MAST_HCI010.csv',
 'DEGs/SS2/met_vs_primary/MAST_J53353.csv',
 'DEGs/SS2/met_vs_primary/MAST_H3204.csv',
 'DEGs/SS2/met_vs_primary/MAST_H5471.csv',
 'DEGs/SS2/met_vs_primary/MAST_J2036.csv',
 'DEGs/SS2/met_vs_primary/MAST_HCI011.csv']

In [4]:
final_met_genes = pd.DataFrame()
final_tumor_genes = pd.DataFrame()

for i in sort_DEGs_all_results_list:
    temp_met_df = pd.DataFrame()
    temp_tumor_df = pd.DataFrame()
    tumor_ID = i.split('.')[0].split('MAST_')[1]
    df = pd.read_csv(i,index_col = 0)
    df = df[df['p_val'] < 0.05]
    met_genes = df[df['avg_log2FC'] > 0.5].sort_values(by='avg_log2FC', ascending=False).index.tolist()
    tumor_genes = df[df['avg_log2FC'] < -0.5].sort_values(by='avg_log2FC', ascending=False).index.tolist()
    
    temp_met_df[tumor_ID] = met_genes
    temp_tumor_df[tumor_ID] = tumor_genes
    
    
    final_met_genes = pd.concat([final_met_genes,temp_met_df], ignore_index=False, axis=1)
    final_tumor_genes = pd.concat([final_tumor_genes,temp_tumor_df], ignore_index=False, axis=1)

In [5]:
final_met_genes

,HCI001,H4272,HCI009,global,J55454,H5097,HCI005,HCI010,J53353,H3204,H5471,J2036,HCI011
0,IGFBP3,KRT6B,GSN,CEACAM6,CTSZ,MTCO1P12,PSCA,HSPA6,KRT16,KRT17,SNX12,HSPA6,MUC5AC
1,CHI3L1,CLIC3,TSPAN1,KRT14,CRELD2,MTCO3P12,TSPAN1,BAG3,CDK6,KRT81,FABP5,KRT17,ANXA2
2,LALBA,RPA1,CGA,PSCA,TMBIM1,TMSB4X,BPIFB1,DNAJB1,TACSTD2,TMSB4X,DNAJC1,MMP7,GSN
3,DDIT4,S100A6,ATP6AP1,CGA,CISD2,POTEKP,CEACAM6,TNFRSF11B,PIGQ,KRT16,AC092171.5,SAT1,KRT81
4,FRZB,KLK6,CEACAM5,KLK6,MRFAP1,MTRNR2L8,FKBP4,PLAU,QPCT,TAGLN,CKS1B,MTND2P28,S100P
...,...,...,...,...,...,...,...,...,...,...,...,...,...
708,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ESF1,NaN,NaN
709,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TMEM167A,NaN,NaN
710,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PIPSL,NaN,NaN
711,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KRAS,NaN,NaN
712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WBP11,NaN,NaN

In [6]:
final_tumor_genes

,HCI001,H4272,HCI009,global,J55454,H5097,HCI005,HCI010,J53353,H3204,H5471,J2036,HCI011
0,PGK1,CHI3L1,TMEM9B-AS1,EEF1A1P5,RPS29,TXNDC12,MT-CO3,MEST,DRG2,UBBP4,COA1,ATP5PO,RAE1
1,SELENON,ZNF346,TOX3,RPL30,RPL41P1,AKR7A2,ECI2,SAA1,HDAC9,IL17RC,TM9SF2,YEATS4,RNF114
2,SNRPB,RSF1,AC012485.3,ANGPTL4,NCL,CORO2A,PGRMC1,MST1R,AC020916.1,AL354702.1,TTC1,CCDC86,PSME2
3,SLC1A5,DYNC2LI1,ANKRD13D,PRSS23,LSR,GINS3,TMPRSS3,PLOD2,NECAP1,RBFOX2,TADA3,ERBB2,AKIP1
4,HSP90AA1,YPEL5,AC010320.3,TGFBI,MAP2K2,H3F3B,ENO1,LAT2,ARF5,CNOT2,CEBPB,NDUFC1,HNRNPC
...,...,...,...,...,...,...,...,...,...,...,...,...,...
749,NaN,NaN,NEAT1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
750,NaN,NaN,EGR1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
751,NaN,NaN,JUN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
752,NaN,NaN,ELF3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
753,NaN,NaN,MAFB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
final_met_genes.to_csv('SS2_met_vs_primary_met_genes_list.csv')
final_tumor_genes.to_csv('SS2_met_vs_primary_tumor_genes_list.csv')